/** @type {Record<string, React.CSSProperties>} */
const s = {
  root: {
    minHeight: "100vh",
    background: "#f5f3ee",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "40px 16px",
    fontFamily: "'DM Sans', sans-serif",
  },
  card: {
    width: "100%",
    maxWidth: 560,
    background: "#fff",
    border: "1px solid #d8d5ce",
    borderRadius: 16,
    padding: "32px 28px",
    boxShadow: "0 2px 24px rgba(0,0,0,0.06)",
  },

  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  tag: {
    fontSize: 10,
    fontFamily: "'DM Mono', monospace",
    letterSpacing: 2,
    color: "#7a7870",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  title: {
    fontSize: 26,
    fontWeight: 600,
    color: "#1a1a18",
    letterSpacing: -0.5,
  },
  counter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    background: "#f5f3ee",
    borderRadius: 12,
    padding: "10px 18px",
  },
  counterNum: {
    fontSize: 28,
    fontWeight: 600,
    color: "#2a52be",
    lineHeight: 1,
    fontFamily: "'DM Mono', monospace",
  },
  counterLabel: {
    fontSize: 11,
    color: "#7a7870",
    textTransform: "uppercase",
    letterSpacing: 1,
  },

  flash: {
    fontSize: 13,
    borderRadius: 8,
    padding: "8px 14px",
    marginBottom: 16,
    transition: "opacity 0.3s",
    fontWeight: 500,
    minHeight: 34,
    display: "flex",
    alignItems: "center",
  },

  addRow: {
    display: "flex",
    gap: 8,
    marginBottom: 6,
  },
  input: {
    flex: 1,
    border: "1px solid #d8d5ce",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 14,
    color: "#1a1a18",
    background: "#fff",
    fontFamily: "'DM Sans', sans-serif",
    transition: "border-color 0.15s",
  },
  btnAdd: {
    background: "#2a52be",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "10px 18px",
    fontSize: 14,
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  error: {
    fontSize: 12,
    color: "#c0392b",
    marginBottom: 10,
  },

  toolbar: {
    display: "flex",
    gap: 8,
    marginBottom: 16,
    flexWrap: "wrap",
  },
  filterGroup: {
    display: "flex",
    gap: 4,
  },
  filterBtn: {
    fontSize: 12,
    border: "1px solid #d8d5ce",
    borderRadius: 6,
    padding: "6px 10px",
    background: "#fff",
    color: "#7a7870",
    whiteSpace: "nowrap",
  },
  filterActive: {
    background: "#eef1fb",
    borderColor: "#2a52be",
    color: "#2a52be",
    fontWeight: 500,
  },

  list: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    minHeight: 40,
  },
  empty: {
    textAlign: "center",
    fontSize: 14,
    padding: "32px 0",
    color: "#aaa",
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#faf9f7",
    border: "1px solid #ece9e2",
    borderRadius: 10,
    padding: "10px 14px",
  },
  itemNum: {
    fontFamily: "'DM Mono', monospace",
    fontSize: 12,
    color: "#aaa9a0",
    width: 22,
    flexShrink: 0,
  },
  itemText: {
    flex: 1,
    fontSize: 14,
    color: "#1a1a18",
  },
  actions: {
    display: "flex",
    gap: 4,
  },
  btnEdit: {
    background: "none",
    border: "1px solid #d8d5ce",
    borderRadius: 6,
    width: 30,
    height: 30,
    fontSize: 14,
    color: "#555",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  btnDel: {
    background: "none",
    border: "1px solid #f0d0d0",
    borderRadius: 6,
    width: 30,
    height: 30,
    fontSize: 12,
    color: "#c0392b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  editRow: {
    display: "flex",
    gap: 8,
    flex: 1,
    alignItems: "center",
  },
  btnSave: {
    background: "#2a52be",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "7px 14px",
    fontSize: 13,
  },
  btnCancel: {
    background: "#f5f3ee",
    color: "#555",
    border: "1px solid #d8d5ce",
    borderRadius: 6,
    padding: "7px 14px",
    fontSize: 13,
  },

  footer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
    paddingTop: 16,
    borderTop: "1px solid #ece9e2",
  },
  footerInfo: {
    fontSize: 12,
    color: "#aaa",
  },
  btnClear: {
    fontSize: 12,
    color: "#c0392b",
    background: "none",
    border: "1px solid #f0d0d0",
    borderRadius: 6,
    padding: "5px 12px",
  },
};

export default s;
